name = "oncf-230"
main = ".open-next/worker.js"

compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

minify = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }
